# 列ごとに分割されたURLリスト
Lists = [
    [
        'https://oai-business.com/laundry/',
        'https://oai-business.com/channel/',
        'https://oai-business.com/dmmfx/'
    ],
    [
        'https://oai-business.com/de/',
        'https://oai-business.com/madoguchi/',
        'https://oai-business.com/hikaku/',
        'https://oai-business.com/shiftlab/',
        'https://oai-business.com/garden/',
        'https://oai-business.com/baby/',
        'https://oai-business.com/tsunaguba/',
        'https://oai-business.com/isuto/',
        'https://oai-business.com/zi-ru/',
        'https://oai-business.com/e-kao/',
        'https://oai-business.com/uzuz/',
        'https://oai-business.com/taku/',
        'https://oai-business.com/jp/',
        'https://ai-beauty-health.com/agaf/',
        'https://ai-beauty-health.com/aga/',
        'https://oai-business.com/20dai/',
        'https://oai-business.com/u-gaku/',
        'https://oai-business.com/mystyle/',
        'https://oai-business.com/avance/',
        'https://oai-business.com/paypro/',
        'https://oai-business.com/suma/',
        'https://oai-business.com/techhub/',
        'https://oai-business.com/kasaihokenshinsei/'
    ],
    [
        'https://etsuko-business.com/lab/',
        'https://etsuko-business.com/laundry/',
        'https://etsuko-business.com/channel/',
        'https://etsuko-business.com/zxy/',
        'https://etsuko-beauty-health.com/art/',
        'https://etsuko-business.com/dmmfx/'
    ],
    [
        'https://etsuko-business.com/de/',
        'https://etsuko-business.com/madoguchi/',
        'https://etsuko-business.com/hikaku/',
        'https://etsuko-beauty-health.com/rita/',
        'https://etsuko-business.com/shiftlab/',
        'https://etsuko-business.com/garden/',
        'https://etsuko-business.com/baby/',
        'https://etsuko-business.com/tsunaguba/',
        'https://etsuko-business.com/zero/',
        'https://etsuko-business.com/isuto/',
        'https://etsuko-business.com/zi-ru/',
        'https://etsuko-business.com/e-kao/',
        'https://etsuko-business.com/uzuz/',
        'https://etsuko-beauty-health.com/ibiki/',
        'https://etsuko-business.com/teppen/',
        'https://etsuko-business.com/taku/',
        'https://etsuko-business.com/jp/',
        'https://etsuko-beauty-health.com/agaf/',
        'https://etsuko-beauty-health.com/aga/',
        'https://etsuko-beauty-health.com/abc/',
        'https://etsuko-business.com/u-gaku/',
        'https://etsuko-business.com/mystyle/',
        'https://etsuko-business.com/avance/',
        'https://etsuko-business.com/paypro/',
        'https://etsuko-business.com/suma/',
        'https://etsuko-business.com/techhub/',
        'https://etsuko-business.com/kasaihokenshinsei/'
    ],
    [
        'https://sajeed-business.com/channel/'
    ],
    [
        'https://sajeed-business.com/de/',
        'https://sajeed-business.com/hikaku/',
        'https://sajeed-business.com/garden/',
        'https://sajeed-business.com/baby/',
        'https://sajeed-business.com/e-kao/',
        'https://sajeed-beauty-health.com/agaf/',
        'https://sajeed-beauty-health.com/aga/',
        'https://sajeed-business.com/paypro/',
        'https://sajeed-business.com/selectnavi/',
        'https://sajeed-business.com/avance/',
        'https://sajeed-business.com/rightus/'
    ],
    [
        'https://shige-business.com/lab/',
        'https://shige-business.com/laundry/',
        'https://shige-business.com/channel/',
        'https://shige-business.com/zxy/',
        'https://shige-beauty-health.com/art/',
        'https://shige-beauty-health.com/abc/',
        'https://shige-business.com/dmmfx/'
    ],
    [
        'https://shige-business.com/minna/',
        'https://shige-business.com/uzuz/'
    ],
    [
        'https://shige-business.com/mammoth/'
    ],
    [
        'https://shige-beauty-health.com/rias/',
        'https://shige-business.com/tsunaguba/',
        'https://shige-beauty-health.com/agaf/',
        'https://shige-beauty-health.com/aga/'
    ],
    [
        'https://shige-business.com/jpre/'
    ],
    [
        'https://suhjuwon-business.com/laundry/',
        'https://suhjuwon-business.com/channel/'
    ],
    [
        'https://suhjuwon-business.com/de/',
        'https://suhjuwon-business.com/hikaku/',
        'https://suhjuwon-business.com/garden/',
        'https://suhjuwon-business.com/baby/',
        'https://suhjuwon-business.com/e-kao/',
        'https://suhjuwon-beauty-health.com/agaf/',
        'https://suhjuwon-beauty-health.com/aga/'
    ],
    [
        'https://takuchan-business.com/lab/',
        'https://takuchan-business.com/laundry/',
        'https://takuchan-business.com/channel/',
        'https://takuchan-business.com/zxy/',
        'https://takuchan-beauty-health.com/art/',
        'https://takuchan-beauty-health.com/abc/',
        'https://takuchan-business.com/dmmfx/'
    ],
    [
        'https://takuchan-business.com/tanto/',
        'https://takuchan-business.com/minna/',
        'https://takuchan-business.com/uzuz/',
        'https://takuchan-business.com/techhub/'
    ],
    [
        'https://takuchan-business.com/mammoth/'
    ],
    [
        'https://takuchan-beauty-health.com/rias/',
        'https://takuchan-business.com/garden/',
        'https://takuchan-business.com/tsunaguba/',
        'https://takuchan-beauty-health.com/agaf/',
        'https://takuchan-beauty-health.com/aga/'
    ],
    [
        'https://takuchan-business.com/baby/',
        'https://takuchan-business.com/jp/'
    ],
    [
        'https://takeo-business.com/laundry/',
        'https://takeo-business.com/channel/',
        'https://takeo-business.com/dmmfx/'
    ],
    [
        'https://takeo-business.com/de/',
        'https://takeo-business.com/kasaimadoguchi/',
        'https://takeo-business.com/hikaku/',
        'https://takeo-business.com/kasaihokenshinsei/',
        'https://takeo-business.com/shiftlab/',
        'https://takeo-business.com/garden/',
        'https://takeo-business.com/baby/',
        'https://takeo-business.com/pro/',
        'https://takeo-business.com/bytech/',
        'https://takeo-business.com/thunaguba/',
        'https://takeo-business.com/suma/',
        'https://takeo-business.com/zi-ru/',
        'https://takeo-business.com/e-kao/',
        'https://takeo-business.com/taku/',
        'https://takeo-business.com/jp/',
        'https://takeo-beauty-health.com/agaf/',
        'https://takeo-beauty-health.com/aga/'
    ],
    [
        'https://hoken-kaimei.com/laundry/',
        'https://hoken-kaimei.com/channel/'
    ],
    [
        'https://hoken-kaimei.com/de/',
        'https://tensyoku-kaimei.com/shiftlab/',
        'https://hoken-kaimei.com/garden/',
        'https://hoken-kaimei.com/baby/',
        'https://tensyoku-kaimei.com/tsunaguba/',
        'https://tensyoku-kaimei.com/e-kao/',
        'https://tensyoku-kaimei.com/taku/'
    ],
    [
        'https://noda-business.com/laundry/',
        'https://noda-business.com/channel/',
        'https://noda-business.com/dmmfx/'
    ],
    [
        'https://noda-business.com/de/',
        'https://noda-business.com/hikaku/',
        'https://noda-business.com/kasaihokenshinsei/',
        'https://noda-business.com/shiftlab/',
        'https://noda-business.com/garden/',
        'https://noda-business.com/baby/',
        'https://noda-business.com/bytech/',
        'https://noda-business.com/tsunaguba/',
        'https://noda-business.com/zi-ru/',
        'https://noda-business.com/e-kao/',
        'https://noda-business.com/taku/',
        'https://noda-business.com/jp/',
        'https://noda-beauty-health.com/agaf/',
        'https://noda-beauty-health.com/aga/'
    ],
    [
        'https://hassi--business.com/laundry/',
        'https://hassi--business.com/channel/',
        'https://hassi--business.com/dmmfx/'
    ],
    [
        'https://hassi--business.com/de/',
        'https://hassi--business.com/madoguchi/',
        'https://hassi--business.com/hikaku/',
        'https://hassi--business.com/shiftlab/',
        'https://hassi--business.com/garden/',
        'https://hassi--business.com/baby/',
        'https://hassi--business.com/tsunaguba/',
        'https://hassi--business.com/isuto/',
        'https://hassi--business.com/zi-ru/',
        'https://hassi--business.com/navi/',
        'https://hassi--business.com/e-kao/',
        'https://hassi--business.com/uzuz/',
        'https://hassi--business.com/taku/',
        'https://hassi--business.com/jp/',
        'https://hassi--beauty-health.com/agaf/',
        'https://hassi--beauty-health.com/aga/',
        'https://hassi--business.com/20dai/',
        'https://hassi--business.com/u-gaku/',
        'https://hassi--business.com/mystyle/',
        'https://hassi--business.com/avance/',
        'https://hassi--business.com/paypro/',
        'https://hassi--business.com/suma/',
        'https://hassi--business.com/techhub/',
        'https://hassi--business.com/kasaihokenshinsei/'
    ],
    [
        'https://haruka-business.com/laundry/',
        'https://haruka-business.com/channel/',
        'https://haruka-business.com/dmmfx/'
    ],
    [
        'https://haruka-business.com/de/',
        'https://haruka-business.com/madoguchi/',
        'https://haruka-business.com/hikaku/',
        'https://haruka-business.com/shiftlab/',
        'https://haruka-business.com/garden/',
        'https://haruka-business.com/baby/',
        'https://haruka-business.com/tsunaguba/',
        'https://haruka-business.com/isuto/',
        'https://haruka-business.com/zi-ru/',
        'https://haruka-business.com/e-kao/',
        'https://haruka-business.com/uzuz/',
        'https://haruka-business.com/taku/',
        'https://haruka-business.com/jp/',
        'https://haruka-beauty-health.com/agaf/',
        'https://haruka-beauty-health.com/aga/',
        'https://haruka-business.com/20dai/',
        'https://haruka-business.com/u-gaku/',
        'https://haruka-business.com/mystyle/',
        'https://haruka-business.com/avance/',
        'https://haruka-business.com/paypro/',
        'https://haruka-business.com/suma/',
        'https://haruka-business.com/techhub/',
        'https://haruka-business.com/kasaihokenshinsei/'
    ],
    [
        'https://mimori-business.com/laundry/',
        'https://mimori-business.com/channel/',
        'https://haruka-business.com/dmmfx/'
    ],
    [
        'https://mimori-business.com/de/',
        'https://mimori-business.com/hikaku/',
        'https://mimori-business.com/shiftlab/',
        'https://mimori-business.com/garden/',
        'https://mimori-business.com/baby/',
        'https://mimori-business.com/tsunaguba/',
        'https://mimori-business.com/e-kao/',
        'https://mimori-business.com/taku/',
        'https://mimori-business.com/jp/',
        'https://mimori-beauty-health.com/agaf/',
        'https://mimori-beauty-health.com/aga/',
        'https://mimori-business.com/bytech/',
        'https://mimori-business.com/iekatsu/',
        'https://mimori-business.com/u-gaku/'
    ],
    [
        'https://megu-business.com/laundry/',
        'https://megu-business.com/channel/'
    ],
    [
        'https://megu-business.com/de/',
        'https://megu-business.com/hikaku/',
        'https://megu-business.com/garden/',
        'https://megu-business.com/baby/',
        'https://megu-business.com/techhub/',
        'https://megu-business.com/tsunaguba/',
        'https://megu-business.com/e-kao/',
        'https://megu-business.com/taku/',
        'https://megu-business.com/mystyle/',
        'https://megu-business.com/jp/',
        'https://megu-business.com/fair/',
        'https://megu-beauty-health.com/agaf/',
        'https://megu-beauty-health.com/aga/',
        'https://megu-business.com/bytech/'
    ],
    [
        'https://yuho-business.com/laundry/',
        'https://yuho-business.com/channel/',
        'https://haruka-business.com/dmmfx/'
    ],
    [
        'https://yuho-business.com/de/',
        'https://yuho-business.com/hikaku/',
        'https://yuho-business.com/shiftlab/',
        'https://yuho-business.com/garden/',
        'https://yuho-business.com/baby/',
        'https://yuho-business.com/bytech/',
        'https://yuho-business.com/tsunaguba/',
        'https://yuho-business.com/sukima/',
        'https://yuho-business.com/zi-ru/',
        'https://yuho-business.com/e-kao/',
        'https://yuho-business.com/assets/',
        'https://yuho-business.com/taku/',
        'https://yuho-business.com/jp/',
        'https://yuho-beauty-health.com/agaf/',
        'https://yuho-beauty-health.com/aga/'
    ],
    [
        'https://tomoki-business.com/laundry/',
        'https://tomoki-business.com/channel/',
        'https://tomoki-business.com/dmmfx/'
    ],
    [
        'https://tomoki-business.com/de/',
        'https://tomoki-business.com/hikaku/',
        'https://tomoki-business.com/garden/',
        'https://tomoki-business.com/baby/',
        'https://tomoki-business.com/family/',
        'https://tomoki-business.com/bytech/',
        'https://tomoki-business.com/tsunaguba/',
        'https://tomoki-business.com/ecohonpo/',
        'https://tomoki-business.com/eco/',
        'https://tomoki-business.com/e-kao/',
        'https://tomoki-business.com/taku/',
        'https://tomoki-business.com/jp/',
        'https://tomoki-beauty-health.com/dazzy/',
        'https://tomoki-beauty-health.com/agaf/',
        'https://tomoki-beauty-health.com/aga/'
    ],
    [
        'https://riza-business.com/lab/',
        'https://riza-business.com/laundry/',
        'https://riza-business.com/channel/',
        'https://riza-business.com/zxy/',
        'https://riza-beauty-health.com/art/',
        'https://riza-business.com/dmmfx/'
    ],
    [
        'https://riza-business.com/de/',
        'https://riza-business.com/madoguchi/',
        'https://riza-business.com/tanto/',
        'https://riza-business.com/hikaku/',
        'https://riza-beauty-health.com/rita/',
        'https://riza-beauty-health.com/rias/',
        'https://riza-business.com/shiftlab/',
        'https://riza-business.com/garden/',
        'https://riza-business.com/baby/',
        'https://riza-business.com/bytech/',
        'https://riza-business.com/heart/',
        'https://riza-business.com/tsunaguba/',
        'https://riza-business.com/zero/',
        'https://riza-business.com/isuto/',
        'https://riza-business.com/zi-ru/',
        'https://riza-business.com/e-kao/',
        'https://riza-business.com/uzuz/',
        'https://riza-beauty-health.com/ibiki/',
        'https://riza-business.com/taku/',
        'https://riza-business.com/jp/',
        'https://riza-beauty-health.com/agaf/',
        'https://riza-beauty-health.com/agaskin/',
        'https://riza-beauty-health.com/abc/',
        'https://riza-business.com/u-gaku/',
        'https://riza-business.com/mystyle/',
        'https://riza-business.com/avance/',
        'https://riza-business.com/paypro/',
        'https://riza-business.com/suma/',
        'https://riza-business.com/techhub/',
        'https://riza-business.com/kasaihokenshinsei/'
    ],
    [
        #'https://rui-business.com/laundry/'
    ],
    [
        'https://rui-business.com/de/',
        'https://rui-business.com/hikaku/',
        'https://rui-business.com/lifeshiftlab/',
        'https://rui-business.com/garden/',
        'https://rui-business.com/baby/',
        'https://rui-business.com/tsunaguba/',
        'https://rui-business.com/e-kao/',
        'https://rui-business.com/taku/',
        'https://rui-business.com/jp/',
        'https://rui-beauty-health.com/agaf/',
        'https://rui-beauty-health.com/aga/'
    ],
    [
        'https://kikui-business.com/shiftlab/'
    ],
    [
        'https://reiko-business.com/laundry/',
        'https://reiko-business.com/channel/'
    ],
    [
        'https://reiko-business.com/de/',
        'https://reiko-business.com/hikaku/',
        'https://reiko-business.com/shiftlab/',
        'https://reiko-business.com/garden/',
        'https://reiko-business.com/baby/',
        'https://reiko-business.com/tsunaguba/',
        'https://reiko-business.com/e-kao/',
        'https://reiko-business.com/taku/',
        'https://reiko-business.com/jp/',
        'https://reiko-beauty-health.com/agaf/',
        'https://reiko-beauty-health.com/aga/',
        'https://reiko-business.com/avance/',
        'https://reiko-business.com/rightus/',
        'https://reiko-business.com/paypro/',
        'https://reiko-business.com/selectnavi/'
    ],
    [
        'https://hara-business.com/garden/',
        'https://hara-business.com/de/',
        'https://hara-business.com/e-kao/',
        'https://hara-business.com/shiftlab/',
        'https://hara-business.com/jp/',
        'https://hara-business.com/hikaku/',
        'https://hara-beauty-health.com/aga/',
        'https://hara-beauty-health.com/agaf/'
    ],
    [
        'https://reo-business.com/laundry/'
    ],
    [
        'https://reo-business.com/de/',
        'https://reo-business.com/hikaku/',
        'https://reo-business.com/shiftlab/',
        'https://reo-business.com/garden/',
        'https://reo-business.com/baby/',
        'https://reo-business.com/tsunaguba/',
        'https://reo-business.com/e-kao/',
        'https://reo-business.com/taku/',
        'https://reo-business.com/jp/',
        'https://reo-beauty-health.com/agaf/',
        'https://reo-beauty-health.com/aga/'
    ],
    [
        'https://konno-business.com/laundry/',
        'https://konno-business.com/channel/'
    ],
    [
        'https://konno-business.com/de/',
        'https://konno-business.com/kasaimadoguchi/',
        'https://konno-business.com/hikaku/',
        'https://konno-business.com/kasaihokenshinsei/',
        'https://konno-business.com/shiftlab/',
        'https://konno-business.com/garden/',
        'https://konno-business.com/baby/',
        'https://konno-business.com/pro/',
        'https://konno-business.com/tsunaguba/',
        'https://konno-business.com/suma/',
        'https://konno-business.com/e-kao/',
        'https://konno-business.com/taku/',
        'https://konno-business.com/jp/',
        'https://konno-beauty-health.com/agaf/',
        'https://konno-beauty-health.com/aga/'
    ],
    [
        'https://sakairi-business.com/laundry/'
    ],
    [
        'https://sakairi-business.com/de/',
        'https://sakairi-business.com/hikaku/',
        'https://sakairi-business.com/shiftlab/',
        'https://sakairi-business.com/garden/',
        'https://sakairi-business.com/baby/',
        'https://sakairi-business.com/tsunaguba/',
        'https://sakairi-business.com/e-kao/',
        'https://sakairi-business.com/taku/',
        'https://sakairi-business.com/jp/',
        'https://sakairi-beauty-health.com/agaf/',
        'https://sakairi-beauty-health.com/aga/'
    ],
    [
        'https://mitani-business.com/laundry/'
    ],
    [
        'https://mitani-business.com/de/',
        'https://mitani-business.com/hikaku/',
        'https://mitani-business.com/shiftlab/',
        'https://mitani-business.com/garden/',
        'https://mitani-business.com/baby/',
        'https://mitani-business.com/tsunaguba/',
        'https://mitani-business.com/e-kao/',
        'https://mitani-business.com/taku/',
        'https://mitani-business.com/jp/',
        'https://mitani-beauty-health.com/agaf/',
        'https://mitani-beauty-health.com/aga/'
    ],
    [
        'https://ryuji-business.com/de/',
        'https://ryuji-business.com/hikaku/',
        'https://ryuji-business.com/garden/',
        'https://ryuji-business.com/jp/',
        'https://ryuji-business.com/shiftlab/',
        'https://ryuji-business.com/e-kao/',
        'https://ryuji-business.com/taku/',
        'https://ryuji-beauty-health.com/agaf/',
        'https://ryuji-beauty-health.com/aga/'
    ],
    [
        'https://marie-business.com/laundry/',
        'https://marie-business.com/channel/'
    ],
    [
        'https://marie-business.com/de/',
        'https://marie-business.com/hikaku/',
        'https://marie-business.com/shiftlab/',
        'https://marie-business.com/garden/',
        'https://marie-business.com/baby/',
        'https://marie-business.com/tsunaguba/',
        'https://marie-business.com/sukima/',
        'https://marie-business.com/e-kao/',
        'https://marie-business.com/taku/',
        'https://marie-business.com/jp/',
        'https://marie-beauty-health.com/agaf/',
        'https://marie-beauty-health.com/aga/'
    ],
    [
        'https://sugiyama-business.com/laundry/'
    ],
    [
        'https://sugiyama-business.com/de/',
        'https://sugiyama-business.com/hikaku/',
        'https://sugiyama-business.com/shiftlab/',
        'https://sugiyama-business.com/garden/',
        'https://sugiyama-business.com/baby/',
        'https://sugiyama-business.com/tsunaguba/',
        'https://sugiyama-business.com/e-kao/',
        'https://sugiyama-business.com/taku/',
        'https://sugiyama-business.com/jp/',
        'https://sugiyama-beauty-health.com/agaf/',
        'https://sugiyama-beauty-health.com/aga/'
    ],
    [
        'https://koichi-business.com/laundry/'
    ],
    [
        'https://koichi-business.com/de/',
        'https://koichi-business.com/hikaku/',
        'https://koichi-business.com/shiftlab/',
        'https://koichi-business.com/salon/',
        'https://koichi-business.com/search/',
        'https://koichi-business.com/garden/',
        'https://koichi-business.com/baby/',
        'https://koichi-business.com/tsunaguba/',
        'https://koichi-business.com/e-kao/',
        'https://koichi-business.com/taku/',
        'https://koichi-business.com/jp/',
        'https://koichi-beauty-health.com/agaf/',
        'https://koichi-beauty-health.com/aga/'
    ],
    [
        'https://muraoka-business.com/laundry/'
    ],
    [
        'https://muraoka-business.com/de/',
        'https://muraoka-business.com/hikaku/',
        'https://muraoka-business.com/garden/',
        'https://muraoka-business.com/e-kao/',
        'https://muraoka-business.com/taku/',
        'https://muraoka-beauty-health.com/agaf/',
        'https://muraoka-beauty-health.com/aga/'
    ],
    [
        'https://oshima-business.com/laundry/'
    ],
    [
        'https://oshima-business.com/de/',
        'https://oshima-business.com/hikaku/',
        'https://oshima-business.com/shiftlab/',
        'https://oshima-business.com/garden/',
        'https://oshima-business.com/baby/',
        'https://oshima-business.com/e-kao/',
        'https://oshima-business.com/taku/',
        'https://oshima-business.com/jp/',
        'https://oshima-beauty-health.com/agaf/',
        'https://oshima-beauty-health.com/aga/'
    ],
    [
        'https://yuichi-business.com/laundry/',
        'https://yuichi-business.com/channel/'
    ],
    [
        'https://yuichi-business.com/de/',
        'https://yuichi-business.com/hikaku/',
        'https://yuichi-business.com/shiftlab',
        'https://yuichi-business.com/garden/',
        'https://yuichi-business.com/baby/',
        'https://yuichi-business.com/tsunaguba/',
        'https://yuichi-business.com/e-kao/',
        'https://yuichi-business.com/iekatsu/',
        'https://yuichi-business.com/u-gaku/',
        'https://yuichi-business.com/taku/',
        'https://yuichi-business.com/jp/',
        'https://yuichi-beauty-health.com/agaf/',
        'https://yuichi-beauty-health.com/aga/'
    ],
    [
        'https://jyunichi-business.com/laundry/'
    ],
    [
        'https://jyunichi-business.com/de/',
        'https://jyunichi-business.com/hikaku/',
        'https://jyunichi-business.com/shiftlab/',
        'https://jyunichi-business.com/garden/',
        'https://jyunichi-business.com/baby/',
        'https://jyunichi-business.com/tsunaguba/',
        'https://jyunichi-business.com/e-kao/',
        'https://jyunichi-business.com/taku/',
        'https://jyunichi-business.com/jp/',
        'https://jyunichi-beauty-health.com/agaf/',
        'https://jyunichi-beauty-health.com/aga/'
    ],
    [
        'https://masao-business.com/laundry/',
        'https://masao-business.com/channel/'
    ],
    [
        'https://masao-business.com/de/',
        'https://masao-business.com/hikaku/',
        'https://masao-business.com/garden/',
        'https://masao-business.com/baby/',
        'https://masao-business.com/e-kao/',
        'https://masao-business.com/taku/',
        'https://masao-business.com/jp/',
        'https://masao-beauty-health.com/agaf/',
        'https://masao-beauty-health.com/aga/'
    ],
    [
        'https://kihara-business.com/laundry/',
        'https://kihara-business.com/channel/'
    ],
    [
        'https://kihara-business.com/de/',
        'https://kihara-business.com/hikaku/',
        'https://kihara-business.com/shiftlab/',
        'https://kihara-business.com/garden/',
        'https://kihara-business.com/baby/',
        'https://kihara-business.com/tsunaguba/',
        'https://kihara-business.com/e-kao/',
        'https://kihara-business.com/taku/',
        'https://kihara-business.com/jp/',
        'https://kihara-beauty-health.com/agaf/',
        'https://kihara-beauty-health.com/aga/'
    ],
    [
        'https://arima-business.com/laundry/',
        'https://arima-business.com/channel/'
    ],
    [
        'https://arima-business.com/de/',
        'https://arima-business.com/hikaku/',
        'https://arima-business.com/shiftlab/',
        'https://arima-business.com/garden/',
        'https://arima-business.com/baby/',
        'https://arima-business.com/techhub/',
        'https://arima-business.com/tsunaguba/',
        'https://arima-business.com/e-kao/',
        'https://arima-business.com/taku/',
        'https://arima-business.com/mystyle/',
        'https://arima-business.com/jp/',
        'https://arima-business.com/fair/',
        'https://arima-beauty-health.com/agaf/',
        'https://arima-beauty-health.com/aga/'
    ],
    [
        'https://takashima-business.com/lab/',
        'https://takashima-business.com/laundry/',
        'https://takashima-business.com/neo/',
        'https://takashima-business.com/tane/'
    ],
    [
        'https://takashima-business.com/de/',
        'https://takashima-business.com/hikaku/',
        'https://takashima-business.com/shiftlab/',
        'https://takashima-business.com/garden/',
        'https://takashima-business.com/baby/',
        'https://takashima-business.com/e-kao/',
        'https://takashima-business.com/taku/',
        'https://takashima-business.com/jp/',
        'https://takashima-beauty-health.com/agaf/',
        'https://takashima-beauty-health.com/aga/'
    ],
    [
        'https://doi-business.com/garden/',
        'https://doi-beauty-health.com/aga/',
        'https://doi-beauty-health.com/agaf/',
        'https://doi-business.com/de/',
        'https://doi-business.com/e-kao/',
        'https://doi-business.com/jp/',
        'https://doi-business.com/shiftlab/',
        'https://doi-business.com/hikaku/'
    ]
]
